version: "3.7"
services:

  ### MySQL Container
  mysql:
      build:
          context: ./mysql
          args:
              - MYSQL_DATABASE=${MYSQL_DATABASE}
              - MYSQL_USER=${MYSQL_USER}
              - MYSQL_PASSWORD=${MYSQL_PASSWORD}
              - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
          - "${MYSQL_PORT}:3306"

 ### Flask web app 
  dsi324:
    build: ./web/.
    ports:
      - 5000:5000
    volumes:
      - ./web/.:/code
    environment:
      FLASK_ENV: development
